### PR TITLE
Experimental esm loader

### PR DESCRIPTION
**Pull request by Brooooooklyn**
- Close: https://github.com/Brooooooklyn/swc-node/issues/634
- Close: https://github.com/Brooooooklyn/swc-node/issues/383
- Close: https://github.com/Brooooooklyn/swc-node/issues/120

### CODE REVIEW

**Comment by Multiply** [comment]
We're eagerly waiting for top-level await support.

Can we do anything to help test this?

**Comment by DenisGorbachev** [comment]
Stuck on ESM support as well, looking forward to this PR merge!

**Comment by sam-goodwin** [comment]
Is something blocking this change from being merged?

**Comment by osdiab** [comment]
also waiting for this!

**Comment by weyert** [comment]
Any way how to progress this PR?

**Comment by foray1010** [comment]
`esm` folder is not included in v1.6.0, so `@swc-node/register/esm` does not work

```
> cat node_modules/@swc-node/register/package.json | rg version
  "version": "1.6.0",

> ls node_modules/@swc-node/register
LICENSE  README.md  index.js  lib  node_modules  package.json  read-default-tsconfig.d.ts  register.d.ts
```

Also, seems `node -r @swc-node/register/esm` is using `require()`, it failed to recognize `/esm`

```
Error: Package subpath './esm' is not defined by "exports" in node_modules/@swc-node/register/package.json
```

**Comment by jensbodal** [comment]
Can someone shed some light on how to use this now that it's fixed?

**test.ts**
```
import got from 'got';

const { data } = await got
  .post('https://httpbin.org/anything', {
    json: {
      hello: 'world',
    },
  })
  .json<{data: unknown}>();

console.log(data);
```

```
node -r @swc/register test.ts
```

```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /foo/test.ts
```

**Comment by erfanium** [comment]
@jensbodal you should use `loader` for esm
```
node --loader @swc-node/register/esm test.ts
```

**Comment by jensbodal** [comment]
Thank you that worked

**Comment by weyert** [comment]
Can we use both `-r` and `--loader` at the same time? Or does that not make sense?

**Comment by erfanium** [comment]
@weyert 
You can use. but i can't tell you something makes sense or not without seeing the actual code.

**Pull request merged**
